### ISSUE TITLE
Lässt sich nicht aktivieren

### ISSUE THREAD

**Issue by Latz** [obstschale/bookmark-manager#13]
Frische installation:

Warning: require(/home/latz/www/bookmarks/wp-content/plugins/bookmark-manager/vendor/autoload.php): failed to open stream: No such file or directory in /home/latz/www/bookmarks/wp-content/plugins/bookmark-manager/bookmark-manager.php on line 38

**Comment by obstschale** [comment]
Hast du das ZIP [hier](https://github.com/obstschale/bookmark-manager/releases/tag/v0.1.0) runterladen oder das git repo?

**Comment by Latz** [comment]
Ich habe das repo gecloned.

**Comment by obstschale** [comment]
Ja, das dachte ich mir. Das Repo enthält kein lauffähiges Plugin. Denn ich arbeite mit Composer, NPM und Webpack. Diese Tools laden oder erstellen Dateien, daher speichert man die nicht im Repo.

Deshalb werde ich zu jedem Release ein Plugin zippen, dass man direkt so installieren kann. Ergo, wenn du nicht entwickelst, sondern nur testen willst lade immer die letzte Version hier runter als ZIP: [bookmark-manager/releases](https://github.com/obstschale/bookmark-manager/releases)

**Comment by obstschale** [comment]
Ich werde das später noch mal ausführlicher in die README schreiben. Hatte gestern Nacht dazu aber keine Lust mehr ^^

**Comment by Latz** [comment]
Danke! Mit dem ZIP funktioniert das Plugin. Ich werde erstmal nur ein bisschen testen und meckern. Mal sehen, ob ich ein wenig mit entwickle (evtl. Import), aber dazu müsste ich mich erstmal mit Composer, npm, webpack und Laravel beschäftigen. Wollte ich mal machen, wäre mal eine gute Gelegenheit.

**Comment by obstschale** [comment]
Super 👍 

Genau teste erstmal und wenn was nicht klappt melde dich einfach. :)
