### ISSUE TITLE
Firefox returns true in main window

### ISSUE THREAD

**Issue by Latz** [obstschale/bookmark-manager#17]
Firefox: wenn ich das Bookmarkelt-Popup öffne, wird der Javascript-Code im gebookmarkten Tab übernommen und es wird "true" angezeigt:
![2017-06-26_20-57-15](https://user-images.githubusercontent.com/633642/27556083-779abd10-5ab4-11e7-8692-a46e36b1248e.png)

Opera und Chrome öffnen kein Popup, sondern im Hauptfenster:
![2017-06-26_21-32-41](https://user-images.githubusercontent.com/633642/27556736-11724a28-5ab7-11e7-9b6e-79687a25be68.png)

IE 11: funktioniert.

Alles auf Windows 7. Ist das nur bei mir so oder ist das reproduzierbar oderliegt das an meiner wilden Knfiguration?

**Comment by obstschale** [comment]
Also in Chrome funktioniert es bei mir. Aber Firefox verhält sich genau so. Hab gestern noch andere Bugs gefunden. Bookmarklets programmieren ist echt schwierig hab ich festgestellt, weil jeder Browser sich anders verhält.

**Comment by obstschale** [comment]
Ich nutze dieses Issue mal alleine für den Firefox bug.

**Comment by obstschale** [comment]
see: https://stackoverflow.com/questions/43259253/javascript-bookmarklet-outputting-true-in-firefox-instead-of-performing-script

>Try wrapping in in void
>
>`javascript:void(function(){$("#ruleDetailForm\\.authorizingStatutes").val("Test")}());`

Das hat bei mir funktioniert. Werde es im nächsten Release einbauen

**Comment by Latz** [comment]
Das Scriptlet funktioniert jetzt ebenfalls bei mir. Javascript ist eine große Wundertüte, in der man immer was Neues findet.
