### ISSUE TITLE
Plugin oder Stand-Alone

### ISSUE THREAD

**Issue by obstschale** [obstschale/bookmark-manager#2]
Die Diskussion im Blog hat ja schon die Frage aufgeworfen, ob man das ganze als CPT (Custom Post Type) und somit als Plugin oder eigenständige WP Instanz realisiert. Es gibt für beide Seiten Pros und Cons und das will ich hier noch mal genauer diskutieren.

**Comment by obstschale** [comment]
## Mein erster Gedanke

Der Beitrag war ja erstmal nur die Idee. Ich habe ja nur Gedanken niedergeschrieben, die man diskutieren kann und noch nicht in Stein gemeißelt sind. Allerdings war mein erster Gedanke es wirklich als eigene Webseite aufzuziehen. Ich finde den Gedanken attraktiver eine eigene WP Instanz zu haben, die sich nur um dieses eine Feature, nämlich Bookmarks verwalten, kümmert. Dann könnte man genau für diesen Zweck die Webseite optimieren, mit Themes und Plugins noch anreichern.

Sicherlich kann man das auch als Plugin realisieren. Für mich ist es gerade nicht wirklich wichtig, dass viele Nutzer das einfach installieren und dann mit machen, sondern ich wollte eine Lösung für _mich_, wo ich einfach nur meine Links speichere.

Dieser "Soziale Aspekt" macht das ganze ja erst so kompliziert, dass man dann gewisse Standards / Richtlinien festlegen muss, damit Webseiten untereinander Daten austauschen können. 

Ich habe mir daher das ganze so vorgestellt, dass man eine eigene Webseite hat und die dafür optimiert, aber mit so wenig Aufwand wie möglich. Wenn ich nämlich eine Webseite nur für dieses eine Ziel habe kann ich alle Funktionen, die WordPress schon mit sich bringt, auch dafür verwenden. Sprich, warum einen neuen CPT anlegen wenn `Posts` das schon kann? Ich müsste dann also nur noch ein Theme schreiben, dass die Links sauber darstellt und fertig ist die Kiste.

**Comment by wp-entwickler-at** [comment]
servus. wie im blog schon geschrieben, bin ich für eine plugin-lösung.
logischerweise gehören dann auch stylings und plugin-theme-dateien dazu.

mir isses aber im ersten schritt wurscht, wie wir das lösen.

hauptsache die sache nimmt fahrt auf!
mfg
souri

**Comment by Latz** [comment]
Ich hatte im Block ja auch schon mehrmals betont, dass mich das Projekt vor allem deshalb interessiert, weil es einen interessanten und ungewöhnlichen Ansatz verfolgt. Die Gretchenfrage ist: Wollen wir ein massentaugliches Plugin, dass möglichst viele nutzen wollen oder wollen wir etwas, dass uns glücklich macht? Ich weiß, die Fragestellung ist voreingenommen.

Wie @obstschale oben schreibt, ist es einfacher, eine dedizierte WP-Installation zu verwenden, weil man das System dann kompromisslos ausnutzen kann. Man kommt schnell zu einem nutzbaren Ergebnis, das dann nach und nach verbessert und erweitert werden kann.

Wenn es allerdings nur zwei Leute sind, die das System nutzen wollen, dann würde ich eher zu einem Standard-Plugin-Ansatz tendieren.

Mein Vorschlag: Wir versuchen, in den nächsten Tagen noch einige Meinungen abzuwarten. Im Zweifelsfall hat @obstschale  das Problem der Entscheidung...

**Comment by websupporter** [comment]
Ich finde beides attraktiv. Falls es nicht über einen eigenen CPT gelöst wird sondern mit `post` wäre ich dafür, dass ganze im `post_format` `link` zu tun. Sozusagen der Nachfolger der `wp_links`, wenn ichs richtig sehe.

Das hätte dann (allerdings mE wirklich für irgendwann einmal, erstmal Ball flachhalten) den interessanten Effekt, dass man bspw. Video-Bookmarks (nach discovery) als `post_format` `video` ablegen könnte, Audio-Bookmarks als `audio` etc.

Hmm... Das spricht eigentlich wirklich gegen nen CPT.

---

Ach sorry, das hat gar nix mit Plugin/Theme-Entscheidung zu tun...

**Comment by Latz** [comment]
@websupporter Schön, Dir beim denken zusehen zu können :-) 

Die Idee mit den Post-Formaten finde ich sehr gut und ein gutes Argument.

**Comment by websupporter** [comment]
Ich denke, wir werden über die Frage Plugin/Theme eine bessere Entscheidung treffen, wenn wir uns Gedanken über die Features gemacht haben. Nur, weil ich es gerade durchlese:

Import/Export-Feature gehört für mich nicht in ein Theme. Aber das ganze in grün ist für mich Theme.

Na gut, also meine zwei Pfennige: Beides! Anhand der Features dann eine Entscheidung, gehört dieses Feature in das Plugin oder das Theme und beide kooperieren dann eben 1a zusammen (Stichwort `add_theme_support()`, wir könnten ja `bookmarks` nehmen)

**Comment by obstschale** [comment]
Danke @websupporter für den Einwand mit `post_formats`. Das hatte ich anfangs auch schon überlegt. Es gab aber, wenn ich mich richtig erinnere, mal Überlegungen diese Funktion aus dem Core zu entfernen und dann als Plugin anzubieten (nur zu Infos, würde ja unser Vorgehen nicht behindern). Da ich kein Theme-Guy bin korrigiert mich wenn ich falsch liege, aber die `post_format`s müsse im Theme angegeben werden nur dann erscheinen sie im Backend. Also wenn das Theme diese Funktion nicht unterstütz kannst du auch keinen Link Post Format auswählen.

Das wäre kein Problem, wenn wir eine eigene Lösung stricken und nicht auf Plugin und Theme Unabhängigkeit setzen.

**Comment by obstschale** [comment]
Antwort auf meinen eigenen Gedanken: Post Formats sind eigentlich ein Theme feature, damit im Frontend unterschiedliche Templates verwendet werden können. Aber eigentlich ist das ja nicht unser Ziel. Also ich für meinen Teil brauche nur eine Liste mit Links (und den Beschreibungen) in einer Chronologischen-Auflistung. Wenn man Links nach Video, Audio, etc. kategorisieren will würde ich wohl einfach Tags verwenden und fertig.

Ich würde sogar soweit gehen und gar keine Kategorien verwenden. Mit Tags kann ich persönlich genau so gut Kategorien abbilden und auch Tag Bundles erstellen (Tag Bundles müsste man dann mit einem Plugin nachrüsten).

**Comment by websupporter** [comment]
Das Plugin würd den Post speichern und `set_post_format()` machen. Was das Theme dann daraus macht ist dem Theme überlassen. Aber ich glaube das müsste gehen.

**Comment by wp-entwickler-at** [comment]
post-format zu verwenden find ich eine schlechte idee. wie von @obstschale erwähnt, könnte die funktion aus dem core wandern.
es gibt sicher leute, die post-formate aber noch verwenden und vielleicht für den post/cpt bookmarks gerne verwenden würden.

**Comment by websupporter** [comment]
Hat jemand einen Link dazu, dass die das einfach so rausschmeißen? Würde mich mal interessieren, wie das von statten gehen soll bzgl. Abwärtskompatibilität.

post-format muss aber nicht, da hängt mein Herzblut jetzt nicht dran.

**Comment by Soean** [comment]
Hier wurde zuletzt über post formats diskutiert: 
http://wptavern.com/new-proposal-on-trac-to-remove-post-formats-from-wordpress-core
https://core.trac.wordpress.org/ticket/32844

**Comment by websupporter** [comment]
Danke! Not convinced though. Ein paar Leute schlagen vor das rauszunehmen. 

> Resolution set to wontfix 

Naja. Aber `post-format` muss nicht. Falls wir da nochmal auf das Thema kommen würde ich das als neuen Issue vorschlagen. Habe hier schon genug das falsche Topic gekapert und ich glaub, soweit sind wir eigentlich noch nicht in der Planung.

**Comment by obstschale** [comment]
Eine Sache, die ich mir noch überlegt habe ist: Wenn ich Links als `post` speichere muss man irgendwie einen Standard festlegen, wie URL und Beschreibung aussehen sollten falls beides im `the_content` drin sein sollte.

Ich denke es wäre "besser" wenn der Link gleich in einem meta Feld gespeichert würde, weil das das Auslesen für's Theme und eine mögliche API leichter macht. 

Das müsste dann aber 1) mit eine Plugin noch nachgerüstet werden und 2) im Bookmarklet möglich sein. 
Und wenn wir dafür ein Plugin benötigen, dann stellt sich mir die Frage, warum nicht gleich ein eigener CPT, das wäre nicht so viel mehr Aufwand und man kann es eben doch im Verbindung mit einem Blog nutzen.

**Comment by Latz** [comment]
@obstschale: Ich komme auch mehr und mehr zu der Einsicht, dass ein CPT die bessere Lösung ist. Ein reiner Post ist zwar einfach zu erzeugen, aber eben sehr unflexibel. 

In den nächsten drei Wochen habe ich leider etwas weniger Zeit. Mal sehen, was ich gebastelt kriege.

**Comment by obstschale** [comment]
Ich arbeite jetzt and einem Plugin mit eigenen `Bookmarks` Post Type. Das ist für mich der sinnvollste Weg um in Zukunft flexible zu bleiben.

**Comment by wp-entwickler-at** [comment]
+1
