### ISSUE TITLE
Start

### ISSUE THREAD

**Issue by wp-entwickler-at** [obstschale/bookmark-manager#5]
Fangen wir mal an? ;-)
Magst ein Grundgerüst reinstellen?
Und wir fügen nach und nach Code aus den anderen Plugins zum Testen ein?
Oder wie wollen wir das im ersten (Versuchs-)Schritt angehen?

**Comment by Latz** [comment]
Ich bastel gerade am Bookmarklet; das ein Post erstellt, das nur Folgendes enthält:

> <href a="http://superseite.de">Superseite</a>
> http://www.superseite.de
> Beschreibung der Seite

Prinzipiell habe ich das Post-This-Bookmarklet gekapert und mit einem Filter den Content reduziert. (Das normale Press-This funktioniert jetzt nicht mehr, was bei dem Ansatz mit einem Extra-Blog ja auch nicht mehr genutzt wird.)

Das ist nicht viel, aber prinzipiell ist das eigentlich schon ausreichend, wenn man "post" als Posttype nimmt. Wenn man jetzt ein Theme drumrum baut, ist das eigentlich schon alles.

Automatische Tags und Kategorien scheinen schwieriger zu werden.

**Comment by Latz** [comment]
Meinen ersten Versuch ein Bookmark-Post zu erstellen kann man sich hier ansehen, einfach nur um mal zu sehen, ob es klappt. Nichts Aufregendes.

https://github.com/Latz/WordPress-Bookmarks/ 

Unter Options->Social Bookmarks findet man nach der Aktivierung des Plugins ein Bookmarklet. 

Voraussetzung ist PHP >= v5.3, weil ich mit einem Closure arbeite.

**Comment by obstschale** [comment]
Kuckuck. Die Uni hat letzte Wochen etwas Aufmerksamkeit haben wollen. Deshalb musste ich hier erstmal pausieren.

Zurück zum Thema: Ich würde nächste Woche mal mit dem Projekt anfangen und einfach testweise, wie @Latz, loslegen und ausprobieren. Es gibt noch ein paar Gedanken die ich gleich in #2 erörtern möchte. Aber es ist nun mal ein Side-Projekt, dass langsam voran geht ;)

**Comment by obstschale** [comment]
So ich habe jetzt doch schon angefangen. Mein Bookmarks findet ihr unter https://bookmarks.hanshelgebuerger.de

Ich habe mal das Bookmarklet von @Latz installiert. Das klappt ja schon mal gut 👍  Ich speicher jetzt einfach mal über die Tage meine Bookmarks ab und guck was mich nervt und wo ich was ändern würde.

**Comment by Latz** [comment]
Ich habe mal was Neues gebastelt.
- spezielles Popup statt "PressThis"
- Tags und Beschreibung werden von der Webseite importiert und im Post gespeichert.

**Update:** Die Regex hat anscheinend Fehler und funktioniert nur auf einigen Seiten.

Das Teil ist noch in einem sehr frühen Stadium. Es gibt logischerweise vieles was man weiter entwickeln muss. Auf Anhieb fallen mir folgende Dinge ein:
- Die Tags und die Beschreibung werden über PHP gezogen, indem die Seite noch einmal neu geladen wird. Das Problem war, dass a) die Größe eines Bookmarklets beschränkt und b) ist Cross-Site-Scripting ein Problem ist. Somit ist eine reine Javascript-Lösung eher schlecht. 
- Das PHP-Skript läuft momentan noch synchron und blockiert somit das Popup. Asynchron wäre gut für eine bessere User Experience. 
- Die Daten werden als normales Post gespeichert. CPT sind die bessere Lösung.
- Der Code muss zur Kapselung noch in Klassen verpackt werden.
-  Vieles, vieles mehr.

Das neue Plugin ist hier: https://github.com/Latz/bookmark_it

(Das Bookmarklet muss neu in die Bookmarks gezogen werden.)

**Comment by Latz** [comment]
Ich habe mittlerweile mal etwas weiter gemacht und einen CPT eingeführt. Hat etwas länger gedauert, weil ich ein paar Probleme beim Popup gab (ich hatte keine Init-Action um den CPT zu registirieren).
Im Moment bastle ich an einem kleinen Theme auf _s-Basis. Nächste Woche schiebe ich mal ein Zwischenergebnis auf Github.

**Comment by obstschale** [comment]
Klasse. Ich bin leider etwas im Arbeitsstress und finde keine Zeit dafür. Wollte aber im September, wenn ich Urlaub habe, mal wieder das Thema angehen.

Ich denke der CPT ist der richtige Weg. Ich würde nämlich dann erstmal nur das Plugin (mit Bookmarklet) nutzen um die Seiten zu speichern und würde später gerne mal mit der REST API diese Daten wieder anzapfen und ein eigene Theme mit JS (Vue.js) bauen :)

**Comment by Latz** [comment]
Hier mal ein Schnappschuss meiner bisherigen Arbeit als Anhang. (Kein eigenes Repo, weil ich einfach zu doof bin, GitHub richtig zu bedienen)

Die größten Neuerungen sind die Einführung eines Custom Post Types und etwas Ajax. Bei mir auf dem Dev-Server läuft ganz gut, keine Ahnung wie es sich woanders verhält.

Ich habe ein sehr, sehr schlechtes Theme hinzu gepackt ("Bookmarks"), in dem der Custom Post Type angezeigt wird (Habe einfach das Underscore-Theme missbraucht)

[bookmarks.2.zip](https://github.com/obstschale/WordPress-Bookmarks/files/439425/bookmarks.2.zip)

**Comment by obstschale** [comment]
Danke @Latz  / Das bietet erstmal ne gute Grundlage um anzufangen. Werde deine Idee in mein Plugin mal umsetzen.

**Comment by wp-entwickler-at** [comment]
ich frag mich ehrlich, warum wir da nicht vom fleck kommen :DDD

**Comment by obstschale** [comment]
War halt ein volles Jahr ^^ aber ich hab ja jetzt angefangen, kannst ja mal in den `develop` branch gucken.
